// export interface PageStateInterface {
// }


export  enum PageState {
  Initial,
  Loading,
  Success,
  Failed,
  Empty,
}
// class PageStateHolder {
//   readonly Initial: PageState = {}
//   readonly Loading: PageState = {}
//   readonly Success: PageState = {}
//   readonly Failed: PageState = {}
//   readonly Empty: PageState = {}
// }
//
// const PageState = new PageStateHolder()

export default PageState