

export class Resources {
  static readonly bg = $r('app.media.bg');
  static readonly icon_back = $r('app.media.icon_back');
  static readonly icon_home_cart = $r('app.media.icon_home_cart');
  static readonly icon_home_message = $r('app.media.icon_home_message');
  static readonly icon_home_search = $r('app.media.icon_home_search');
  static readonly icon_project_not_selected = $r('app.media.icon_project_not_selected');

  static readonly exit = $r('app.media.exit');
  static readonly logo = $r('app.media.logo');

  static readonly icon = $r('app.media.icon');
  static readonly mine = $r('app.media.mine');

  static readonly icon_home_pager_not_selected = $r('app.media.icon_home_pager_not_selected');
  static readonly new_enter_button = $r('app.media.new_enter_button');

  static readonly icon_knowledge_hierarchy_not_selected = $r('app.media.icon_knowledge_hierarchy_not_selected');
  static readonly startIcon = $r('app.media.startIcon');

  static readonly icon_navigation_not_selected = $r('app.media.icon_navigation_not_selected');



}